name: firebase-deploy-hosting

on:
    push:
      branches: [ dev ]
    pull_request:
      branches: [ master, dev ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install dependencies
        working-directory: Plattform
        run: npm install
      - name: build
        working-directory: Plattform
        run: npm run build
      - name: archive build
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: Plattform/public
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download build
        uses: actions/download-artifact@v2
        with:
          name: public
          path: Plattform/public
      - name: deploy
        uses: w9jds/firebase-action@dev
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ FIREBASE_TOKEN }}