name: firebase-deploy-hosting

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install dependencies
        working-directory: Plattform
        run: npm install
      - name: build
        working-directory: Plattform
        run: npm run build
      - name: archive build
        uses: actions/upload-artifact@master
        with:
          name: public
          path: Plattform/public
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download build
        uses: actions/download-artifact@master
        with:
          name: public
          path: Plattform/public
      - name: set short sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --message ${{ steps.vars.outputs.sha_short }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          # https://stackoverflow.com/questions/58352402/how-to-add-working-directory-to-deployment-in-github-actions
          PROJECT_PATH: ./Plattform